// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/cce31af92dc06fbd620d48ff55a9904be20ddc61/koa-compress/index.d.ts
declare module "koa-compress" {

    import * as Koa from "koa";
    import * as zlib from "zlib";

    interface CompressOptions extends zlib.ZlibOptions {
        /**
         * An optional function that checks the response content type to decide whether to compress. By default, it uses compressible.
         */
        filter?: (content_type: string) => boolean;

        /**
         * Minimum response size in bytes to compress. Default 1024 bytes or 1kb.
         */
        threshold?: number
    }

    /**
     * Compress middleware for Koa
     */
    function compress(options?: CompressOptions): Koa.Middleware;

    namespace compress {}
    export = compress;
}
